CREATE TABLE users(id BIGSERIAL PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,role VARCHAR(50) NOT NULL DEFAULT 'CUSTOMER');
CREATE TABLE products(id BIGSERIAL PRIMARY KEY,name VARCHAR(255) NOT NULL,sku VARCHAR(100) UNIQUE NOT NULL,category VARCHAR(100),price NUMERIC(12,2) NOT NULL,stock INTEGER NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE);
